#!/usr/bin/env python3
"""Run the OTLP smoke test locally against the real collector.

This script reuses the same diagnostic handler function that Snowflake calls in
`app/python/otlp_export_smoke_test.py`, so it exercises the same exporter init
and payload-construction path without needing a Snowflake runtime.
"""

from __future__ import annotations

import argparse
import importlib
import json
import sys
import uuid
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[1]
APP_PYTHON = PROJECT_ROOT / "app" / "python"
DEFAULT_ENDPOINT = "otelcol.israelcentral.cloudapp.azure.com:4317"
DEFAULT_PEM = PROJECT_ROOT / "grpc_test" / "tls-setup" / "ca.crt"

if str(APP_PYTHON) not in sys.path:
    sys.path.insert(0, str(APP_PYTHON))


def _load_smoke_module():
    """Import the Snowflake diagnostic module after sys.path setup."""
    return importlib.import_module("otlp_export_smoke_test")


def run_local_smoke(
    endpoint: str,
    pem_path: Path,
    test_id: str | None = None,
) -> dict[str, object]:
    """Execute the same handler used by the Snowflake diagnostic procedure."""
    smoke_module = _load_smoke_module()
    resolved_test_id = test_id or f"local_smoke_{uuid.uuid4().hex[:12]}"
    pem_text = pem_path.read_text(encoding="utf-8")
    raw_result = smoke_module.test_otlp_export_runtime(
        None,
        endpoint,
        pem_text,
        resolved_test_id,
    )
    return json.loads(raw_result)


def main() -> int:
    """Parse CLI args, run smoke test, and print structured JSON."""
    parser = argparse.ArgumentParser(
        description="Run the local OTLP runtime smoke test against the real collector.",
    )
    parser.add_argument(
        "endpoint",
        nargs="?",
        default=DEFAULT_ENDPOINT,
        help=f"OTLP gRPC endpoint (default: {DEFAULT_ENDPOINT})",
    )
    parser.add_argument(
        "--pem",
        type=Path,
        default=DEFAULT_PEM,
        help=f"Path to collector CA PEM (default: {DEFAULT_PEM})",
    )
    parser.add_argument(
        "--test-id",
        help="Optional unique test id; autogenerated when omitted.",
    )
    args = parser.parse_args()

    if not args.pem.exists():
        print(f"PEM file not found: {args.pem}", file=sys.stderr)
        return 1

    result = run_local_smoke(args.endpoint, args.pem, args.test_id)
    print(json.dumps(result, indent=2, sort_keys=True))

    if "init_error" in result:
        return 1

    signal_results = (
        result.get("span_export") is True
        and result.get("log_export") is True
        and result.get("metric_export") is True
    )
    return 0 if signal_results else 1


if __name__ == "__main__":
    raise SystemExit(main())
